name: Build and Deploy to Fly.io

on:
  push:
    branches:
      - main
jobs:
  build-and-deploy:
    name: Build and deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/setup-buildx-action@v2
      - run: |
          docker build -t linpaul:latest .
        

      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
